/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/item/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["item_list"];
        put?: never;
        post: operations["item_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/item/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["item_retrieve"];
        put: operations["item_update"];
        post?: never;
        delete: operations["item_destroy"];
        options?: never;
        head?: never;
        patch: operations["item_partial_update"];
        trace?: never;
    };
    "/api/item/home/feed/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["item_home_feed_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/item/my-clippings/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["item_my_clippings_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/item/my-clippings/create/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["item_my_clippings_create_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review/account/{username}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["review_account_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review/create/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Leave a review
         * @description Create a review for either an item or a user account.
         *
         *     - Set `about` to `item` to review an item
         *     - Set `about` to `account` to review a seller/buyer
         *
         *     The request body changes depending on the value of `about`.
         */
        post: operations["review_create_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review/item/{item_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["review_item_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/{id}/socials/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get socials of the user users */
        get: operations["user_socials_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/{id}/verify/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify a user
         * @description Verifies the chosen account
         */
        post: operations["user_verify_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/avatar/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["user_avatar_retrieve"];
        put?: never;
        post: operations["user_avatar_create"];
        delete: operations["user_avatar_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/by_username/{username}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["user_by_username_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/delete/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["user_delete_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/list/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["user_list_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["user_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["user_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["user_refresh_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["user_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/unverified/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get unverified users
         * @description Retrieve the current list of unverified users.
         */
        get: operations["user_unverified_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/update_socials/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["user_update_socials_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description * `item` - item
         *     * `account` - account
         * @enum {string}
         */
        AboutEnum: "item" | "account";
        AccountReview: {
            readonly id: number;
            /** Format: decimal */
            rating: string;
            comment?: string | null;
            /** Format: date-time */
            readonly created_at: string;
            seller: number;
        };
        AccountReviewSerializerIncoming: {
            /** Format: decimal */
            rating: string;
            comment?: string | null;
            offer: number;
        };
        /** @description Mixin to handle image uploads for any model with a GenericRelation to Image */
        AvatarUpload: {
            /** Format: uri */
            image: string;
        };
        Image: {
            readonly id: number;
            /** Format: uri */
            image: string;
            /** Format: int64 */
            order?: number;
        };
        Item: {
            readonly id: number;
            readonly seller: components["schemas"]["PublicUserInfo"];
            readonly images: components["schemas"]["Image"][];
            title: string;
            description: string;
            /** Format: decimal */
            price: string;
            /** Format: int64 */
            stock?: number;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            negotiable?: boolean;
            /** Format: decimal */
            min_negotiable_price?: string | null;
            tags?: number[];
        };
        ItemBasic: {
            readonly id: number;
            title: string;
            /** Format: decimal */
            price: string;
            /** Format: int64 */
            stock?: number;
            negotiable?: boolean;
            seller: components["schemas"]["SellerUser"];
            /** Format: decimal */
            readonly rating: string;
            readonly thumbnail: string | null;
        };
        ItemReview: {
            readonly id: number;
            /** Format: decimal */
            rating: string;
            comment?: string | null;
            /** Format: date-time */
            readonly created_at: string;
            item: number;
        };
        PaginatedItemBasicList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["ItemBasic"][];
        };
        PatchedItem: {
            readonly id?: number;
            readonly seller?: components["schemas"]["PublicUserInfo"];
            readonly images?: components["schemas"]["Image"][];
            title?: string;
            description?: string;
            /** Format: decimal */
            price?: string;
            /** Format: int64 */
            stock?: number;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
            negotiable?: boolean;
            /** Format: decimal */
            min_negotiable_price?: string | null;
            tags?: number[];
        };
        /**
         * @description * `facebook` - Facebook
         *     * `youtube` - YouTube
         *     * `instagram` - Instagram
         *     * `whatsapp` - WhatsApp
         *     * `twitter` - X (Twitter)
         *     * `snapchat` - Snapchat
         *     * `linkedin` - LinkedIn
         *     * `pinterest` - Pinterest
         *     * `email` - Email
         * @enum {string}
         */
        PlatformEnum: "facebook" | "youtube" | "instagram" | "whatsapp" | "twitter" | "snapchat" | "linkedin" | "pinterest" | "email";
        PublicUserInfo: {
            readonly id: number;
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username: string;
            is_verified_seller?: boolean;
            readonly avatar: components["schemas"]["Image"][];
        };
        SellerUser: {
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username: string;
            is_verified_seller?: boolean;
        };
        SerializerWithAbout: {
            /** Format: decimal */
            rating: string;
            comment?: string | null;
            offer: number;
            /**
             * @description Determines which serializer should process this review
             *
             *     * `item` - item
             *     * `account` - account
             */
            about: components["schemas"]["AboutEnum"];
        };
        SocialLink: {
            readonly id: number;
            platform: components["schemas"]["PlatformEnum"];
            /** Format: uri */
            url?: string;
            user: number;
        };
        User: {
            readonly id: number;
            readonly avatar: components["schemas"]["Image"][];
            password: string;
            /** Format: date-time */
            last_login?: string | null;
            /**
             * Superuser status
             * @description Designates that this user has all permissions without explicitly assigning them.
             */
            is_superuser?: boolean;
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username: string;
            first_name?: string;
            last_name?: string;
            /**
             * Email address
             * Format: email
             */
            email?: string;
            /**
             * Staff status
             * @description Designates whether the user can log into this admin site.
             */
            is_staff?: boolean;
            /**
             * Active
             * @description Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
             */
            is_active?: boolean;
            /** Format: date-time */
            date_joined?: string;
            phone?: string;
            is_verified_seller?: boolean;
            /** @description The groups this user belongs to. A user will get all permissions granted to each of their groups. */
            groups?: number[];
            /** @description Specific permissions for this user. */
            user_permissions?: number[];
        };
        UserBasic: {
            readonly id: number;
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username: string;
            first_name?: string;
            last_name?: string;
        };
        UserRegister: {
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username: string;
            /** Format: email */
            email: string;
            password: string;
            first_name: string;
            last_name: string;
            /** @default false */
            is_staff: boolean;
            /** @default false */
            is_superuser: boolean;
        };
        UserSocialWithGlint: {
            socials: components["schemas"]["SocialLink"][];
            glint: boolean;
        };
        loginOKResponse: {
            token: string;
            id: number;
            username: string;
            role: string;
        };
        redusedTokenPair: {
            username: string;
            password: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    item_list: {
        parameters: {
            query?: {
                /** @description Number of results to return per page. */
                amount?: number;
                e?: boolean;
                /** @description A page number within the paginated result set. */
                page?: number;
                q?: string;
                t?: string;
                u?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedItemBasicList"];
                };
            };
        };
    };
    item_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Item"];
                "application/x-www-form-urlencoded": components["schemas"]["Item"];
                "multipart/form-data": components["schemas"]["Item"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"];
                };
            };
        };
    };
    item_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this item. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"];
                };
            };
        };
    };
    item_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this item. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Item"];
                "application/x-www-form-urlencoded": components["schemas"]["Item"];
                "multipart/form-data": components["schemas"]["Item"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"];
                };
            };
        };
    };
    item_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this item. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    item_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this item. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedItem"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedItem"];
                "multipart/form-data": components["schemas"]["PatchedItem"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"];
                };
            };
        };
    };
    item_home_feed_list: {
        parameters: {
            query?: {
                /** @description Number of results to return per page. */
                amount?: number;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description The users latest */
                search?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedItemBasicList"];
                };
            };
        };
    };
    item_my_clippings_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemBasic"];
                };
            };
        };
    };
    item_my_clippings_create_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    review_account_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountReview"][];
                };
            };
        };
    };
    review_create_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SerializerWithAbout"];
                "application/x-www-form-urlencoded": components["schemas"]["SerializerWithAbout"];
                "multipart/form-data": components["schemas"]["SerializerWithAbout"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountReviewSerializerIncoming"];
                };
            };
        };
    };
    review_item_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemReview"][];
                };
            };
        };
    };
    user_socials_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this user. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSocialWithGlint"];
                };
            };
        };
    };
    user_verify_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this user. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["User"];
                "application/x-www-form-urlencoded": components["schemas"]["User"];
                "multipart/form-data": components["schemas"]["User"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    user_avatar_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvatarUpload"];
                };
            };
        };
    };
    user_avatar_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["AvatarUpload"];
                "application/x-www-form-urlencoded": components["schemas"]["AvatarUpload"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvatarUpload"];
                };
            };
        };
    };
    user_avatar_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    user_by_username_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    user_delete_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    user_list_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserBasic"][];
                };
            };
        };
    };
    user_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["redusedTokenPair"];
                "application/x-www-form-urlencoded": components["schemas"]["redusedTokenPair"];
                "multipart/form-data": components["schemas"]["redusedTokenPair"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["loginOKResponse"];
                };
            };
        };
    };
    user_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    user_refresh_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie: {
                refresh_token: string;
            };
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["loginOKResponse"];
                };
            };
        };
    };
    user_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRegister"];
                "application/x-www-form-urlencoded": components["schemas"]["UserRegister"];
                "multipart/form-data": components["schemas"]["UserRegister"];
            };
        };
        responses: {
            /** @description User created. No body */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRegister"];
                };
            };
        };
    };
    user_unverified_list: {
        parameters: {
            query?: {
                /** @description Search based on username */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserBasic"][];
                };
            };
        };
    };
    user_update_socials_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["User"];
                "application/x-www-form-urlencoded": components["schemas"]["User"];
                "multipart/form-data": components["schemas"]["User"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
}
